import { mkdir, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import type { LaunchRequest } from '../shared/types';

const sessionPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/iu;

export const parseLaunchUrl = (value: string): LaunchRequest | null => {
  try {
    const url = new URL(value);
    const provider = url.searchParams.get('provider');
    const sessionId = url.searchParams.get('sessionId');
    return url.protocol === 'llmcollaboration:' && url.hostname === 'new-project'
      && (provider === 'codex' || provider === 'claude') && !!sessionId && sessionPattern.test(sessionId)
      ? { provider, sessionId } : null;
  } catch { return null; }
};

const codexSkill = `---
name: llm-collaboration
description: 현재 Codex 채팅을 LLM Collaboration 앱의 새 협업 프로젝트에 연결합니다. 사용자가 "LLM콜라보레이션 하자", "LLM Collaboration 하자", 또는 현재 채팅을 Codex·Claude 협업으로 옮기자고 요청할 때 사용합니다.
---

<!-- Generated by LLM Collaboration -->

현재 Codex 채팅을 협업 앱에 연결하세요. 현재 채팅 ID는 환경 변수 CODEX_THREAD_ID 또는 CODEX_SESSION_ID에서 읽으세요. Windows에서는 PowerShell로 아래 명령을 실행하세요.

\`\`\`powershell
$conversationId = if ($env:CODEX_THREAD_ID) { $env:CODEX_THREAD_ID } else { $env:CODEX_SESSION_ID }
if (-not $conversationId) { throw '현재 Codex 채팅 ID를 찾지 못했습니다.' }
Start-Process "llmcollaboration://new-project?provider=codex&sessionId=$conversationId"
\`\`\`

macOS에서는 \`open "llmcollaboration://new-project?provider=codex&sessionId=$CODEX_THREAD_ID"\`를 실행하세요. 앱에 새 프로젝트 창이 열리면 사용자에게 그 창에서 폴더와 프로젝트 이름을 확인하라고 알려 주세요. 앱 링크가 등록되지 않았으면 LLM Collaboration을 한 번 실행한 뒤 다시 시도하세요.
`;

const claudeSkill = `---
name: llm-collaboration
description: 현재 Claude Code 채팅을 LLM Collaboration 앱의 새 협업 프로젝트에 연결합니다. 사용자가 "LLM콜라보레이션 하자", "LLM Collaboration 하자", 또는 현재 채팅을 Codex·Claude 협업으로 옮기자고 요청할 때 사용합니다.
---

<!-- Generated by LLM Collaboration -->

현재 Claude Code 채팅을 협업 앱에 연결하세요. 현재 세션 ID는 다음 명령에 삽입된 값입니다: \`${'${CLAUDE_SESSION_ID}'}\`. Windows에서는 PowerShell로 실행하세요.

\`\`\`powershell
Start-Process "llmcollaboration://new-project?provider=claude&sessionId=${'${CLAUDE_SESSION_ID}'}"
\`\`\`

macOS에서는 \`open "llmcollaboration://new-project?provider=claude&sessionId=${'${CLAUDE_SESSION_ID}'}"\`를 실행하세요. 앱에 새 프로젝트 창이 열리면 사용자에게 그 창에서 폴더와 프로젝트 이름을 확인하라고 알려 주세요. 앱 링크가 등록되지 않았으면 LLM Collaboration을 한 번 실행한 뒤 다시 시도하세요.
`;

export const installChatSkills = async (): Promise<string[]> => {
  const destinations = [
    { directory: path.join(os.homedir(), '.codex', 'skills', 'llm-collaboration'), content: codexSkill },
    { directory: path.join(os.homedir(), '.claude', 'skills', 'llm-collaboration'), content: claudeSkill },
  ];
  return Promise.all(destinations.map(async ({ directory, content }) => {
    await mkdir(directory, { recursive: true });
    const file = path.join(directory, 'SKILL.md');
    const previous = await readFile(file, 'utf8').catch((error: NodeJS.ErrnoException) => {
      if (error.code === 'ENOENT') return null;
      throw error;
    });
    if (previous && !previous.includes('<!-- Generated by LLM Collaboration -->')) {
      throw new Error(`기존 스킬을 덮어쓰지 않았습니다: ${file}`);
    }
    await writeFile(file, content, 'utf8');
    return directory;
  }));
};
